- name: create local users
  become: true
  become_user: root
  user:
    name: kotetsu9
    state: present
#    password: "{{ 'kotetsu9' | password_hash('md5') }}" => Hashing results in everytime "changed" 
    password: $1$4MtzI5zq$mzizWSaHRTHczZQfvbrTl0
    shell: /bin/bash
    groups:
      - kotetsu
      - wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
