- name: yum repository Remi for PHP
  become: true
  become_user: root
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: installed
  tags:
    - php

#
# pst (may be...) :
#   
#   # php -v
#   PHP 5.6.33 (cli) (built: Jan  3 2018 13:02:21)
#   Copyright (c) 1997-2016 The PHP Group
#   Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
#
#   # php -m
#   [PHP Modules]
#   bz2
#   calendar
#   Core
#   ctype
#   curl
#   date
#   dom
#   ereg
#   exif
#   fileinfo
#   filter
#   ftp
#   gd
#   gettext
#   hash
#   iconv
#   json
#   ldap
#   libxml
#   mbstring
#   mhash
#   mysql
#   mysqli
#   mysqlnd
#   openssl
#   pcntl
#   pcre
#   PDO
#   pdo_mysql
#   pdo_sqlite
#   Phar
#   posix
#   readline
#   Reflection
#   session
#   shmop
#   SimpleXML
#   snmp
#   sockets
#   SPL
#   sqlite3
#   standard
#   sysvmsg
#   sysvsem
#   sysvshm
#   tokenizer
#   wddx
#   xml
#   xmlreader
#   xmlwriter
#   xsl
#   zip
#   zlib
#
#   [Zend Modules]
#
- name: yum install PHP 5.6 packages
  become: true
  become_user: root
  yum:
    name: "{{ item }}"
    enablerepo: remi-php56
    state: installed
  with_items:
    - php
    - php-devel
    - php-common
    - php-pear
    - php-gd
    - php-dbg
    - php-mbstring
    - php-cli
    - php-mysqlnd
    - php-snmp
    - php-ldap
    - php-intl
    - php-imap
    - php-gmp
  tags:
    - php

- name: copy /etc/php.ini
  become: true
  become_user: root
  template:
    src: php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
  tags:
    - php

