#
# Cacti 1.1.34
#

- name: yum install cacti --enablerepo=epel-testing (cacti 1.1.34 at 20180212)
  become: true
  become_user: root
  yum:
    name: cacti
    enablerepo: epel-testing
    state: installed
  tags:
    - cacti

#- name: copy /etc/php.ini
#  become: true
#  become_user: root
#  template:
#    src: php.ini.j2
#    dest: /etc/php.ini
#    owner: root
#    group: root
#    mode: 0644
#  notify:
#    - restart httpd
#  tags:
#    - php

