#
# tested version:
#   mysql : 5.7.21 MySQL Community Server (GPL)
#   cacti : 1.X
# see.
#   https://docs.cacti.net/manual:100:1_installation#installation
#   http://enog.jp/wp-content/uploads/2017/08/enog46_toyama_cacti.pdf
#

# pre:
#   mysql> show databases;
#   +--------------------+
#   | Database           |
#   +--------------------+
#   | information_schema |
#   | mysql              |
#   | performance_schema |
#   | sys                |
#   +--------------------+
#   4 rows in set (0.34 sec)
- name: create database cacti
  become: true
  become_user: root
  mysql_db:
    name: cacti
    state: present
    encoding: utf8mb4
  tags:
    - cacti
    - db


# pre:
#   mysql> SELECT User, Host FROM mysql.user;
#   +---------------+-----------+
#   | User          | Host      |
#   +---------------+-----------+
#   | mysql.session | localhost |
#   | mysql.sys     | localhost |
#   | root          | localhost |
#   +---------------+-----------+
#   3 rows in set (0.00 sec)
#
# see:
#   https://dev.mysql.com/doc/refman/5.7/en/reserved-users.html
- name: create user cactiuser
  become: true
  become_user: root
  mysql_user:
    name: cactiuser
    priv: 'cacti.*:ALL,GRANT/mysql.time_zone_name:SELECT'
    state: present
  tags:
    - cacti
    - db

