- name: OS base config
  hosts: all
  remote_user: kotetsu
  roles:
    - build_disk
    - build_base_pkg
    - build_local_users
    - build_ntpd
    - build_snmpd
    - build_rbenv
    - build_ruby

- name: rsyslog config
  hosts: rsyslog
  remote_user: kotetsu
  roles:
    - build_rsyslog

- name: syslog-ng config
  hosts: syslog-ng-servers
  remote_user: kotetsu
  roles:
    - build_keepalived_syslog-ng
